language: node_js
node_js: '8'
dist: trusty

addons:
  chrome: stable

git:
  depth: 3

branches:
  only:
    - master
    - /^greenkeeper/.*$/

env:
  global:
    - NODE_ENV=test
    - PORT=3003

script: yarn test

after_success: yarn test:coverage
